(function () {
  const baseImage = "../assets/images/";
  const meals = [
    {
      id: "abacha-ugba",
      tag: "Eastern Classic",
      title: "Abacha & Ugba",
      price: "N6,300",
      calories: "540",
      image: `${baseImage}nkwobi-plate.png`,
      alt: "Abacha and ugba African salad",
      description: "Shredded cassava African salad tossed with ugba, palm oil, peppers, onions and local spices.",
      keywords: ["abacha", "ugba", "african salad", "cassava", "eastern", "naija"],
      tags: ["Style - Eastern", "Spice - Medium", "Serving - Regular", "Ready - 18 min"],
      group: "naija"
    },
    {
      id: "isi-ewu",
      tag: "Eastern Delicacy",
      title: "Isi Ewu",
      price: "N9,500",
      calories: "780",
      image: `${baseImage}nkwobi-plate.png`,
      alt: "Isi ewu goat head delicacy",
      description: "Spicy goat head delicacy finished with palm sauce, utazi, onions and native seasoning.",
      keywords: ["isi ewu", "goat head", "native", "eastern", "spicy"],
      tags: ["Protein - Goat", "Spice - Hot", "Style - Native", "Ready - 35 min"],
      group: "naija"
    },
    {
      id: "ogbono-pounded-yam",
      tag: "Draw Soup",
      title: "Ogbono & Pounded Yam",
      price: "N6,800",
      calories: "760",
      image: `${baseImage}egusi-soup.jpg`,
      alt: "Ogbono soup with pounded yam",
      description: "Rich draw soup with assorted meat, fish notes and smooth pounded yam.",
      keywords: ["ogbono", "draw soup", "pounded yam", "swallow", "native"],
      tags: ["Soup - Ogbono", "Protein - Assorted", "Swallow - Pounded Yam", "Ready - 30 min"],
      group: "naija"
    },
    {
      id: "banga-starch",
      tag: "Delta Bowl",
      title: "Banga Soup & Starch",
      price: "N7,400",
      calories: "790",
      image: `${baseImage}egusi-soup.jpg`,
      alt: "Banga soup with starch",
      description: "Palm nut banga soup with native spices, fish, assorted meat and smooth starch.",
      keywords: ["banga", "starch", "palm nut", "delta", "soup", "swallow"],
      tags: ["Soup - Banga", "Swallow - Starch", "Style - Delta", "Ready - 32 min"],
      group: "naija"
    },
    {
      id: "tuwo-miyan-kuka",
      tag: "Northern Classic",
      title: "Tuwo & Miyan Kuka",
      price: "N6,500",
      calories: "690",
      image: `${baseImage}amala-ewedu-fresh.png`,
      alt: "Tuwo with miyan kuka soup",
      description: "Soft tuwo served with baobab leaf soup, beef and northern-style seasoning.",
      keywords: ["tuwo", "miyan kuka", "northern", "swallow", "soup"],
      tags: ["Style - Northern", "Soup - Kuka", "Serving - Large", "Ready - 28 min"],
      group: "naija"
    },
    {
      id: "masa-suya",
      tag: "Northern Bites",
      title: "Masa & Suya",
      price: "N5,700",
      calories: "610",
      image: `${baseImage}suya-plate.png`,
      alt: "Masa rice cakes with suya",
      description: "Soft rice masa served with smoky beef suya, onions and pepper mix.",
      keywords: ["masa", "suya", "rice cake", "northern", "beef"],
      tags: ["Style - Northern", "Protein - Beef", "Spice - Hot", "Ready - 20 min"],
      group: "grills"
    },
    {
      id: "peppered-snail",
      tag: "Pepper Special",
      title: "Peppered Snail",
      price: "N10,500",
      calories: "460",
      image: `${baseImage}nkwobi-plate.png`,
      alt: "Peppered snail with onions and peppers",
      description: "Tender snail tossed in spicy pepper sauce with onions and sweet peppers.",
      keywords: ["snail", "peppered snail", "pepper", "native", "protein"],
      tags: ["Protein - Snail", "Spice - Hot", "Serving - Regular", "Ready - 25 min"],
      group: "grills"
    },
    {
      id: "oha-soup-fufu",
      tag: "Igbo Soup",
      title: "Oha Soup & Fufu",
      price: "N7,100",
      calories: "750",
      image: `${baseImage}egusi-soup.jpg`,
      alt: "Oha soup with fufu",
      description: "Leafy oha soup with assorted meat, stockfish flavour and soft fufu.",
      keywords: ["oha", "ora", "fufu", "soup", "swallow", "igbo"],
      tags: ["Soup - Oha", "Swallow - Fufu", "Style - Eastern", "Ready - 30 min"],
      group: "naija"
    },
    {
      id: "edikang-ikong",
      tag: "Calabar Soup",
      title: "Edikang Ikong & Wheat",
      price: "N7,600",
      calories: "720",
      image: `${baseImage}egusi-soup.jpg`,
      alt: "Edikang ikong vegetable soup",
      description: "Rich vegetable soup with pumpkin leaves, waterleaf, assorted meat and wheat swallow.",
      keywords: ["edikang ikong", "vegetable soup", "calabar", "wheat", "swallow"],
      tags: ["Soup - Vegetable", "Style - Calabar", "Swallow - Wheat", "Ready - 32 min"],
      group: "naija"
    },
    {
      id: "afang-soup",
      tag: "Calabar Soup",
      title: "Afang Soup & Garri",
      price: "N7,300",
      calories: "710",
      image: `${baseImage}egusi-soup.jpg`,
      alt: "Afang soup with garri",
      description: "Afang leaf soup with waterleaf, assorted meat, smoked fish and garri swallow.",
      keywords: ["afang", "garri", "calabar", "soup", "swallow"],
      tags: ["Soup - Afang", "Swallow - Garri", "Protein - Assorted", "Ready - 32 min"],
      group: "naija"
    },
    {
      id: "efo-riro-pounded-yam",
      tag: "Yoruba Soup",
      title: "Efo Riro & Pounded Yam",
      price: "N6,900",
      calories: "740",
      image: `${baseImage}egusi-soup.jpg`,
      alt: "Efo riro with pounded yam",
      description: "Peppered spinach stew with assorted meat, smoked fish notes and smooth pounded yam.",
      keywords: ["efo riro", "vegetable", "pounded yam", "soup", "yoruba"],
      tags: ["Soup - Efo Riro", "Swallow - Pounded Yam", "Spice - Medium", "Ready - 30 min"],
      group: "naija"
    },
    {
      id: "ila-asepo",
      tag: "Okra Soup",
      title: "Ila Asepo & Eba",
      price: "N6,400",
      calories: "690",
      image: `${baseImage}egusi-soup.jpg`,
      alt: "Okra ila asepo soup with eba",
      description: "Mixed okra soup cooked with seafood notes, beef, peppers and yellow eba.",
      keywords: ["ila asepo", "okra", "eba", "soup", "swallow"],
      tags: ["Soup - Okra", "Swallow - Eba", "Style - Yoruba", "Ready - 26 min"],
      group: "naija"
    },
    {
      id: "gbegiri-ewedu-amala",
      tag: "Owambe Bowl",
      title: "Gbegiri, Ewedu & Amala",
      price: "N6,700",
      calories: "760",
      image: `${baseImage}amala-ewedu-fresh.png`,
      alt: "Amala with gbegiri ewedu and stew",
      description: "The classic trio: amala, bean soup, ewedu and rich pepper stew with assorted beef.",
      keywords: ["gbegiri", "ewedu", "amala", "abula", "yoruba", "swallow"],
      tags: ["Combo - Abula", "Style - Yoruba", "Serving - Large", "Ready - 28 min"],
      group: "naija"
    },
    {
      id: "asaro-yam-porridge",
      tag: "Yam Pot",
      title: "Asaro Yam Porridge",
      price: "N5,400",
      calories: "620",
      image: `${baseImage}plantain-meal.jpg`,
      alt: "Asaro yam porridge",
      description: "Yam porridge simmered in pepper sauce with palm oil, greens and smoked fish flavour.",
      keywords: ["asaro", "yam porridge", "yam", "native", "fish"],
      tags: ["Yam - Porridge", "Style - Native", "Spice - Medium", "Ready - 26 min"],
      group: "naija"
    },
    {
      id: "boiled-yam-egg-sauce",
      tag: "Breakfast",
      title: "Boiled Yam & Egg Sauce",
      price: "N4,900",
      calories: "580",
      image: `${baseImage}plantain-meal.jpg`,
      alt: "Boiled yam with egg sauce",
      description: "Soft yam served with tomato egg sauce, peppers and onions.",
      keywords: ["boiled yam", "egg sauce", "yam", "breakfast"],
      tags: ["Yam - Boiled", "Protein - Egg", "Serving - Regular", "Ready - 18 min"],
      group: "naija"
    },
    {
      id: "ekpang-nkukwo",
      tag: "Efik Special",
      title: "Ekpang Nkukwo",
      price: "N8,200",
      calories: "820",
      image: `${baseImage}plantain-meal.jpg`,
      alt: "Ekpang nkukwo cocoyam dish",
      description: "Cocoyam parcels cooked in rich palm sauce with seafood, vegetables and native spice.",
      keywords: ["ekpang nkukwo", "cocoyam", "efik", "calabar", "native"],
      tags: ["Style - Efik", "Base - Cocoyam", "Serving - Large", "Ready - 38 min"],
      group: "naija"
    },
    {
      id: "ukodo",
      tag: "Delta Pepper Soup",
      title: "Ukodo Yam Pepper Soup",
      price: "N7,800",
      calories: "680",
      image: `${baseImage}hero-jollof-premium.jpg`,
      alt: "Ukodo yam pepper soup",
      description: "Goat meat pepper soup with yam, scent leaf and a deep native broth.",
      keywords: ["ukodo", "yam pepper soup", "goat meat", "delta", "pepper soup"],
      tags: ["Soup - Pepper", "Protein - Goat", "Yam - Soft", "Ready - 34 min"],
      group: "naija"
    },
    {
      id: "goat-meat-pepper-soup",
      tag: "Hot Bowl",
      title: "Goat Meat Pepper Soup",
      price: "N8,000",
      calories: "520",
      image: `${baseImage}hero-jollof-premium.jpg`,
      alt: "Goat meat pepper soup",
      description: "Hot pepper soup with goat meat, local herbs and enough spice for cold evenings.",
      keywords: ["goat meat", "pepper soup", "soup", "spicy"],
      tags: ["Protein - Goat", "Spice - Hot", "Serving - Bowl", "Ready - 30 min"],
      group: "grills"
    },
    {
      id: "asun",
      tag: "Peppered Goat",
      title: "Asun",
      price: "N8,800",
      calories: "620",
      image: `${baseImage}suya-plate.png`,
      alt: "Asun peppered goat meat",
      description: "Smoky goat meat chopped and tossed in hot pepper sauce with onions.",
      keywords: ["asun", "goat meat", "peppered", "grills", "spicy"],
      tags: ["Protein - Goat", "Spice - Hot", "Style - Grilled", "Ready - 24 min"],
      group: "grills"
    },
    {
      id: "gizdodo",
      tag: "Party Side",
      title: "Gizdodo",
      price: "N5,600",
      calories: "620",
      image: `${baseImage}dodo-pepper-sauce.png`,
      alt: "Gizdodo gizzard and plantain",
      description: "Peppered gizzard and fried plantain tossed in sweet-spicy tomato sauce.",
      keywords: ["gizdodo", "gizzard", "dodo", "plantain", "party"],
      tags: ["Protein - Gizzard", "Side - Plantain", "Spice - Medium", "Ready - 22 min"],
      group: "grills"
    },
    {
      id: "puff-puff",
      tag: "Small Chop",
      title: "Puff Puff",
      price: "N2,500",
      calories: "420",
      image: `${baseImage}dessert.jpg`,
      alt: "Puff puff sweet fried dough balls",
      description: "Soft golden puff puff with a light crisp outside and sweet warm centre.",
      keywords: ["puff puff", "small chops", "snack", "sweet"],
      tags: ["Snack - Fried", "Serving - Box", "Sweetness - Mild", "Ready - 12 min"],
      group: "desserts"
    },
    {
      id: "chin-chin",
      tag: "Crunchy Sweet",
      title: "Chin Chin",
      price: "N2,200",
      calories: "390",
      image: `${baseImage}dessert.jpg`,
      alt: "Chin chin crunchy Nigerian snack",
      description: "Crunchy sweet chin chin bites for snacking, sharing or pairing with cold drinks.",
      keywords: ["chin chin", "snack", "dessert", "sweet", "crunchy"],
      tags: ["Snack - Crunchy", "Serving - Pack", "Sweetness - Mild", "Ready - 8 min"],
      group: "desserts"
    },
    {
      id: "zobo-drink",
      tag: "Cold Drink",
      title: "Zobo Drink",
      price: "N1,800",
      calories: "180",
      image: `${baseImage}dessert-vanilla-milkshake.png`,
      alt: "Zobo hibiscus drink",
      description: "Chilled hibiscus drink with ginger, cloves and a fruity finish.",
      keywords: ["zobo", "drink", "hibiscus", "cold", "juice"],
      tags: ["Drink - Cold", "Flavour - Hibiscus", "Serving - Bottle", "Ready - 5 min"],
      group: "desserts"
    },
    {
      id: "chapman",
      tag: "Mocktail",
      title: "Chapman",
      price: "N2,800",
      calories: "260",
      image: `${baseImage}dessert-vanilla-milkshake.png`,
      alt: "Chapman drink",
      description: "Classic Nigerian chapman with citrus, bitters, cucumber and a chilled sparkle.",
      keywords: ["chapman", "drink", "mocktail", "cold"],
      tags: ["Drink - Cold", "Style - Mocktail", "Serving - Glass", "Ready - 6 min"],
      group: "desserts"
    },
    {
      id: "peppered-turkey",
      tag: "Protein Plate",
      title: "Peppered Turkey",
      price: "N8,600",
      calories: "640",
      image: `${baseImage}grilled-chicken.jpg`,
      alt: "Peppered turkey wings",
      description: "Turkey pieces fried, grilled and tossed in spicy pepper sauce.",
      keywords: ["turkey", "peppered turkey", "grills", "protein"],
      tags: ["Protein - Turkey", "Spice - Hot", "Serving - Regular", "Ready - 26 min"],
      group: "grills"
    },
    {
      id: "jollof-turkey",
      tag: "Rice Special",
      title: "Jollof Rice & Turkey",
      price: "N7,900",
      calories: "720",
      image: `${baseImage}jollof-rice.jpg`,
      alt: "Jollof rice with turkey",
      description: "Smoky jollof rice served with peppered turkey and fried plantain.",
      keywords: ["jollof", "rice", "turkey", "plantain", "party"],
      tags: ["Rice - Jollof", "Protein - Turkey", "Side - Plantain", "Ready - 25 min"],
      group: "rice"
    },
    {
      id: "native-rice",
      tag: "Palm Oil Rice",
      title: "Native Rice",
      price: "N6,200",
      calories: "650",
      image: `${baseImage}hero-jollof.jpg`,
      alt: "Native palm oil rice",
      description: "Palm oil rice cooked with peppers, smoked fish flavour, scent leaf and crayfish notes.",
      keywords: ["native rice", "palm oil rice", "rice", "fish", "naija"],
      tags: ["Rice - Native", "Spice - Medium", "Style - Local", "Ready - 24 min"],
      group: "rice"
    },
    {
      id: "seafood-okra",
      tag: "Seafood Soup",
      title: "Seafood Okra & Eba",
      price: "N8,500",
      calories: "710",
      image: `${baseImage}hero-jollof-premium.jpg`,
      alt: "Seafood okra soup with eba",
      description: "Okra soup loaded with fish, prawns, peppers and soft eba.",
      keywords: ["seafood okra", "okra", "eba", "prawns", "fish", "soup"],
      tags: ["Soup - Okra", "Protein - Seafood", "Swallow - Eba", "Ready - 30 min"],
      group: "naija"
    },
    {
      id: "plantain-frittata",
      tag: "Breakfast",
      title: "Plantain Frittata",
      price: "N4,700",
      calories: "520",
      image: `${baseImage}dodo-pepper-sauce.png`,
      alt: "Plantain frittata",
      description: "Baked eggs with plantain, peppers and vegetables for a filling breakfast plate.",
      keywords: ["plantain frittata", "plantain", "egg", "breakfast"],
      tags: ["Protein - Egg", "Side - Plantain", "Serving - Slice", "Ready - 18 min"],
      group: "foreign"
    },
    {
      id: "rice-beans-stew",
      tag: "Everyday Plate",
      title: "Rice, Beans & Stew",
      price: "N5,300",
      calories: "690",
      image: `${baseImage}jollof-rice.jpg`,
      alt: "Rice beans stew and plantain",
      description: "White rice and beans served with rich tomato stew, beef and plantain.",
      keywords: ["rice and beans", "rice", "beans", "stew", "plantain"],
      tags: ["Rice - White", "Beans - Honey", "Side - Plantain", "Ready - 22 min"],
      group: "rice"
    },
    {
      id: "bole-fish",
      tag: "Port Harcourt",
      title: "Bole & Fish",
      price: "N7,000",
      calories: "640",
      image: `${baseImage}plantain-meal.jpg`,
      alt: "Roasted plantain bole with fish",
      description: "Roasted plantain with peppered fish and palm oil sauce.",
      keywords: ["bole", "fish", "roasted plantain", "port harcourt", "plantain"],
      tags: ["Plantain - Roasted", "Protein - Fish", "Style - Street", "Ready - 25 min"],
      group: "grills"
    },
    {
      id: "kilishi",
      tag: "Northern Snack",
      title: "Kilishi",
      price: "N5,500",
      calories: "450",
      image: `${baseImage}suya-plate.png`,
      alt: "Kilishi spicy dried beef",
      description: "Thin spicy dried beef with bold northern seasoning and pepper heat.",
      keywords: ["kilishi", "beef", "northern", "snack", "suya"],
      tags: ["Protein - Beef", "Style - Dried", "Spice - Hot", "Ready - 8 min"],
      group: "grills"
    },
    {
      id: "fish-roll",
      tag: "Snack",
      title: "Fish Roll",
      price: "N2,600",
      calories: "410",
      image: `${baseImage}dessert.jpg`,
      alt: "Nigerian fish roll",
      description: "Crisp pastry roll filled with seasoned fish and pepper notes.",
      keywords: ["fish roll", "snack", "pastry", "fish"],
      tags: ["Snack - Pastry", "Protein - Fish", "Serving - Pair", "Ready - 10 min"],
      group: "foreign"
    }
  ];

  window.DupzExtraMeals = meals;
  window.DupzExtraMealDetails = meals.reduce((details, meal) => {
    details[meal.id] = {
      title: meal.title,
      kicker: meal.tag,
      price: meal.price,
      calories: meal.calories,
      image: meal.image,
      alt: meal.alt,
      description: meal.description,
      tags: meal.tags,
      group: meal.group
    };
    return details;
  }, {});
})();
